version: '2.4'
services:
  samlidp:
    image : kristophjunge/test-saml-idp
    container_name: ${COMPOSE_PROJECT_NAME}_saml_idp
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://app.example.com
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: https://localhost/simplesaml/module.php/saml/sp/saml2-acs.php/test-sp
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: https://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - './test-saml-idp/config/simplesamlphp/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php'
    networks:
      - samlidp

  samlsp:
    build: apache-php74
    container_name: ${COMPOSE_PROJECT_NAME}_saml_sp
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './www:/var/www/app'
      - './apache-php74/sites-available:/etc/apache2/sites-available'
    networks:
      - samlidp



networks:
  samlidp:
    name: samlidp
    driver: bridge
